### ISSUE TITLE
Swift 4 compiler error

### ISSUE THREAD

**Issue by LimChihi** [ruslanskorb/RSKGrowingTextView#11]
I have some issue with Swift 4 compiler error.
My project is base on Swift 4, Xcode 9.1 .
<img width="1552" alt="2017-11-09 10 47 02" src="https://user-images.githubusercontent.com/18307084/32611345-fd1af4c4-c52a-11e7-948e-fcd935eef43e.png">

**Comment by LimChihi** [comment]
I think `@objc` is the leading cause of this issue. The Code run perfect when I delete it all.

**Comment by ruslanskorb** [comment]
You shouldn't add `RSKGrowingTextView.h` to the bridging header. Just add `import RSKGrowingTextView` to the file in which you want to use `RSKGrowingTextView`.

**Comment by LimChihi** [comment]
Hello, Here is a demo.
 I just ` pod 'RSKGrowingTextView'` but do noting. And it show lot of compiler errors.
[Demo.zip](https://github.com/ruslanskorb/RSKGrowingTextView/files/1460176/Demo.zip)

**Comment by LimChihi** [comment]
My project is pure swift project. So delete `@objc` is good enough for me. But it may can't be used in Objective-C project. It may have a better solution. 
Thanks for you open source, it help me a lot.

**Comment by ruslanskorb** [comment]
Your project uses the old version of `RSKGrowingTextView`. You need to run `pod update RSKGrowingTextView` from the command line and everything will work.

**Comment by heyarny** [comment]
Same here.
Just used pod and got plenty of errors inside RSKPlaceholderTextView.
I didn't even started using it. Framework won't compile at all.

**Comment by ruslanskorb** [comment]
@heyarny Please check the version of **RSKGrowingTextView** that you are using.
