### ISSUE TITLE
Growing down

### ISSUE THREAD

**Issue by ohetzendorfer** [ruslanskorb/RSKGrowingTextView#12]
Hello :)
Is it possible to let the UITextView growing down and not only up?

In my case I don't want to place the TextView at the bottom of my view. I want to place it at the top of my view and let it growing down. 

Maybe the screenshot illustrates my issue better:
<img width="360" alt="issue" src="https://user-images.githubusercontent.com/6884842/38036500-1dc69734-32a7-11e8-9ba3-81d02e08ee6e.png">

Best regards,
Oliver

**Comment by ruslanskorb** [comment]
Hi @omastny!

**RSKGrowingTextView** does not specify the direction of growing.
To allow it growing down you just need to pin its top to the bottom of another view. In your case, probably, to the top of superview.

Sincerely,
Ruslan

**Comment by ohetzendorfer** [comment]
Hi @ruslanskorb,

thank you for the prompt reply!
I already set the constraints to the superview. Like in the Screenshot.
<img width="809" alt="screen shot 2018-03-29 at 07 54 16" src="https://user-images.githubusercontent.com/6884842/38072431-84786032-3326-11e8-91b0-2ce0598a16aa.png">

**Comment by ruslanskorb** [comment]
@omastny 
[RSKGrowingTextView.zip](https://github.com/ruslanskorb/RSKGrowingTextView/files/1858773/RSKGrowingTextView.zip) - this is a working example.

**Comment by ohetzendorfer** [comment]
@ruslanskorb 
The issue appears because the Class-Module wasn't set to "RSKGrowingTextView" and so it doesn't initialized the RSKGrowingTextView.

Thank you very much!
