### ISSUE TITLE
Bottom space

### ISSUE THREAD

**Issue by mGraczkowskiDigitalforms** [ruslanskorb/RSKGrowingTextView#13]
Hello,
I found issue with bottom space after wrote again the 6 lines.

Steps: 
1. write 6 lines
2. remove one line
3. write again one line

Now the bottom space is bigger than should. 

<img width="397" alt="screenshot 2018-11-27 at 12 51 19" src="https://user-images.githubusercontent.com/20421645/49080205-29093500-f243-11e8-993b-c7caf36b4e84.png">

**Comment by ruslanskorb** [comment]
@mGraczkowskiDigitalforms Could you provide a minimal test project with your problem?

**Comment by mGraczkowskiDigitalforms** [comment]
@ruslanskorb I was testing your example on github. I only changed background to better see textView.
You can see it on this movie: https://www.dropbox.com/s/jdaln7t5254u1qk/bug.mov?dl=0

**Comment by ruslanskorb** [comment]
@mGraczkowskiDigitalforms Fixed in [4.0.1](https://github.com/ruslanskorb/RSKGrowingTextView/releases/tag/4.0.1) :tada: Thanks for reporting!
