### ISSUE TITLE
Incorrect height when setting text in viewDidLoad()

### ISSUE THREAD

**Issue by jovanpreet** [ruslanskorb/RSKGrowingTextView#14]
Calculate height function returns wrong height because of wrong textView size because view with autoLayout have incorrect size in viewDidLoad

**Comment by jovanpreet** [comment]
Thanks it solved my issue...when are you going to release this version?

**Comment by ruslanskorb** [comment]
Released! 🎉

**Comment by jovanpreet** [comment]
thanks 😅
