### ISSUE TITLE
inputAccessoryView

### ISSUE THREAD

**Issue by umair2ooo** [ruslanskorb/RSKGrowingTextView#15]
It is not expanding if we add in 
UICollectionViewController inputAccessoryView
kindly help me as soon as possible

**Comment by ruslanskorb** [comment]
@umair2ooo Probably, you need to reload your input accessory view. Try `textView.reloadInputViews()`.

**Comment by umair2ooo** [comment]
When should I reload ?
I will be thankful to you if you give a demo code or guide me how to handle it.
Thanks

**Comment by ruslanskorb** [comment]
@umair2ooo If you provide a test project with your problem, maybe I can help you.

**Comment by umair2ooo** [comment]
import UIKit
import RSKGrowingTextView


private let reuseIdentifier = "Cell"

class CV_chat: UICollectionViewController {

    @IBOutlet weak var TV_growing: RSKGrowingTextView!
    
    private let messages = ["asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df UMAIR \n\n\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf",
                            "asd fas",
                            "asd fas df asdf asd f asdf asd f as",
                            "asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df as\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf",
                            "asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df UMAIR \n\n\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf",
                            "asd fas",
                            "asd fas df asdf asd f asdf asd f as",
                            "asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df as\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf",
                            "asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df UMAIR \n\n\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf",
                            "asd fas",
                            "asd fas df asdf asd f asdf asd f as",
                            "asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df as\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf",
                            "asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df UMAIR \n\n\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf",
                            "asd fas",
                            "asd fas df asdf asd f asdf asd f as",
                            "asd fas df asdf asd f asdf asd f asdf as df asdf asd fa sdf adsf as df asd fas df as\na sdf asd fas fa sdf asdf asd fa sdf asdf asf as df sadf asdf asd \n asf as fasd fa sdf asdf asd f asf adsf"]
    
    
    
    
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.TV_growing.delegate = self
    }

    
    
    override var inputAccessoryView: UIView? {
        get {
            return self.TV_growing
        }
    }
    
    override var canBecomeFirstResponder: Bool {
        return true
    }
    
    
    
    
    // MARK: UICollectionViewDataSource
    override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 1
    }
    
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        if indexPath.section < 3 {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: CollCellText.self), for: indexPath) as! CollCellText
            cell.lbl_text.text = self.messages[indexPath.section]
            return cell
        }
        else if indexPath.section >= 3 && indexPath.section <= 6 {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: CollCellText.self), for: indexPath) as! CollCellText
            cell.lbl_text.text = self.messages[indexPath.section]
            return cell
        }
        else {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: CollCellText.self), for: indexPath) as! CollCellText
            cell.lbl_text.text = self.messages[indexPath.section]
            return cell
        }
    }
    
    
    
    override func numberOfSections(in collectionView: UICollectionView) -> Int {
        return self.messages.count
    }
}





//MARK:- UICollectionViewDelegateFlowLayout
extension CV_chat : UICollectionViewDelegateFlowLayout {
    
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        let yourWidthOfLable = ((collectionView.frame.size.width * 74.0641)/100)
        let font = UIFont(name: "Helvetica", size: 17.0)
        
        let expectedHeight = self.heightForLable(text: self.messages[indexPath.section], font: font!, width:yourWidthOfLable )+32 // 32 is padding          16 -- Label -- 16
        
        return CGSize(width: view.frame.width, height: expectedHeight)
    }
}




extension CV_chat {
    func heightForLable(text:String, font:UIFont, width:CGFloat) -> CGFloat{
        // pass string ,font , LableWidth
        let label:UILabel = UILabel(frame: CGRect(x: 0, y: 0, width: width, height: CGFloat.greatestFiniteMagnitude))
        label.numberOfLines = 0
        label.lineBreakMode = NSLineBreakMode.byWordWrapping
        label.font = font
        label.text = text
        label.sizeToFit()
        
        return label.frame.height
    }
}

extension CV_chat: UITextViewDelegate {
    func textViewDidChange(_ textView: UITextView) {
        
        
        if textView.text.contains("\n") {
            self.TV_growing.reloadInputViews()
        }
    }
}

**Comment by umair2ooo** [comment]
I tried to reloadinputViews in "textViewDidChange"
but no luck
this is UICollectionViewController
![screen shot 2019-02-08 at 10 20 46 am](https://user-images.githubusercontent.com/2729279/52460255-3ddf3e80-2b8b-11e9-8282-5f60aa7ed227.png)

**Comment by ruslanskorb** [comment]
@umair2ooo Could you provide *a test project*, not a part of code?

**Comment by umair2ooo** [comment]
actually test project size is greater than 10MB
I tried
let me share a link of dropbox
wait

**Comment by umair2ooo** [comment]
https://www.dropbox.com/s/or79rxupvbra03h/CustomChatView.zip?dl=0

**Comment by umair2ooo** [comment]
There is a bunch of code
just see CV_chat

**Comment by ruslanskorb** [comment]
@umair2ooo ok

**Comment by ruslanskorb** [comment]
1. Use version **4.0.5** of **RSKGrowingTextView** in your Podfile.

```ruby
pod 'RSKGrowingTextView', '4.0.5'
```

2. Instead of setting `self.TV_growing.delegate` in `viewDidLoad()` set `translatesAutoresizingMaskIntoConstraints` of `TV_growing` to `false`.

```swift
self.TV_growing.translatesAutoresizingMaskIntoConstraints = false
```

Everything should work.

**Comment by umair2ooo** [comment]
Awesome...!!
Issue resolved
Thank you very much for your time and prompt reponse :-)
