### ISSUE TITLE
Bug placeholder

### ISSUE THREAD

**Issue by hien352911** [ruslanskorb/RSKGrowingTextView#18]
version 5.0.1
I opened a issue about placeholder in RSKPlaceholderTextView. I have some misstakes. 
It is problem with RSKGrowingTextView. 
My placeholder is 2 row. Ex: "Nhap noi dung nhan xet o day. Toi thieu 50 ki tu."
When i wrote 2 row and remove all, my placeholder display 1 row.

**Comment by ruslanskorb** [comment]
@hien352911 Could you provide steps to reproduce?

**Comment by hien352911** [comment]
I use version 5.0.1 with pod install. In Main.storyboard, i drag UITextView, set custome class to RSKGrowingTextView, and set 4 constraints: centerX, centerY, left = 20, height = 100.
I set placeholder is "Nhập nội dung nhận xét ở đây. Tối thiểu 50 kí tự, tối đa 1000 kí tự" (2 rows). 
I type content until 2 rows and remove all, placeholder display 1 row.

**Comment by ruslanskorb** [comment]
@hien352911 Unfortunately, I can not reproduce the problem. Could you provide a test project?

**Comment by hien352911** [comment]
@ruslanskorb Can i send test project by your email (ruslan.skorb@gmail.com)?

**Comment by ruslanskorb** [comment]
@hien352911 Yes, sure.

**Comment by hien352911** [comment]
@ruslanskorb  
i send test project for you. Can you check it? Thank you

**Comment by ruslanskorb** [comment]
@hien352911 Thank you! I got it.

**Comment by ruslanskorb** [comment]
@hien352911 Fixed in [5.0.2](https://github.com/ruslanskorb/RSKGrowingTextView/releases/tag/5.0.2). 🎉 Thanks for reporting!
