### ISSUE TITLE
IOS 13

### ISSUE THREAD

**Issue by ahmedshakeelpk** [ruslanskorb/RSKGrowingTextView#19]
App crashing on ios 13 Xcode 11.2

-[NSURL init] called; this results in an NSURL instance with an empty URL string. Please use one of the documented NSURL initialization methods instead (initWithString:, initFileURLWithPath:, etc.). This message shown only once.

Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named _UITextLayoutView because no class named _UITextLayoutView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target)'

**Comment by ruslanskorb** [comment]
It's a bug for Xcode 11.2.

**Solution:** Roll back to [previous Xcode release version](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_11.1/Xcode_11.1.xip).

https://stackoverflow.com/a/58660634/2134682
