### ISSUE TITLE
Profile.storyboard: error: IB Designables: Failed to render and update auto layout status

### ISSUE THREAD

**Issue by fury21** [ruslanskorb/RSKGrowingTextView#20]
HI!
I got this error in xcode: Profile.storyboard: error: "IB Designables: Failed to render and update auto layout status dlopen(RSKGrowingTextView.framework, 1): Library not loaded: @rpath/RSKPlaceholderTextView.framework/RSKPlaceholderTextView   Referenced from: RSKGrowingTextView.framework   Reason: image not found"

It's repeats in different projects. After this error showed my storyboard stay invisible..... Fix it pls!
![Снимок экрана 2020-04-07 в 19 46 00](https://user-images.githubusercontent.com/30409500/78696721-7baf3280-7908-11ea-8337-7da26f29ae31.png)

**Comment by fury21** [comment]
I'm try reinstall pod, no effect

**Comment by ruslanskorb** [comment]
@fury21 How do you install **RSKGrowingTextView**? Using Swift Package Manager, CocoaPods, Carthage or something else?

**Comment by ruslanskorb** [comment]
@fury21 I checked your problem on the latest available version of RSKGrowingTextView in Xcode 11.4. Everything works as it should. Let me know if you solved the problem on your side.

**Comment by ruslanskorb** [comment]
@fury21 At the moment, it looks like an Interface Builder problem for me. Feel free to reopen the issue if you have any additional information.
