### ISSUE TITLE
Bug in keyboard dismissing

### ISSUE THREAD

**Issue by zaidiabbas** [ruslanskorb/RSKGrowingTextView#22]
I had used RSKGrowingTextView in my project as a chat or comment TextView.

In this project, I am using IQKeyboardManager
`//MARK:- IQKeyboardManager
        IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.shouldShowToolbarPlaceholder = false
        IQKeyboardManager.shared.shouldResignOnTouchOutside = true
        IQKeyboardManager.shared.disabledToolbarClasses = [CommentsTabVC.self]`

And I had disabled the toolbar to remove the done button.

In my case when clicking on anyplace in the screen the keyboard resigned its first responder and the view goes down again. But when clicking on the textView indicator it makes weird behavior. 

I had tried to override the tap gesture by adding the below code:

`@IBOutlet weak var commentTextView: RSKGrowingTextView!
commentTextView.addTapGesture {
            if self.commentTextView.isFirstResponder{
                self.commentTextView.resignFirstResponder()
            }else{
                self.commentTextView.becomeFirstResponder()
            }
        }`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18144118/94135996-f34c2c00-fe6c-11ea-839a-4496ea9e4d00.gif)

**Comment by ruslanskorb** [comment]
@zaidiabbas What exactly is wrong with `RSKGrowingTextView`? It has nothing to do with the keyboard.

**Comment by zaidiabbas** [comment]
> @zaidiabbas What exactly is wrong with `RSKGrowingTextView`? It has nothing to do with the keyboard.

Don't know if it is an issue in the library or it is from another library. Thank you for clearing that it is not from `RSKGrowingTextView`
