### ISSUE TITLE
SPM Integration error

### ISSUE THREAD

**Issue by AalokParikh** [ruslanskorb/RSKGrowingTextView#23]
I got error while tying to add library through SPM. 

"the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again"

![Screen Shot 2020-10-29 at 3 32 04 PM](https://user-images.githubusercontent.com/1628260/97553844-f2726100-19fb-11eb-948b-c58f33e24fec.png)

**Comment by ruslanskorb** [comment]
@AalokParikh Have you tried to do what is indicated in the error description?

**Comment by ruslanskorb** [comment]
@AalokParikh Feel free to reopen the issue if the problem is not resolved.
