### ISSUE TITLE
Constraints break on UIPasteBoard -> paste action

### ISSUE THREAD

**Issue by cvcoder1** [ruslanskorb/RSKGrowingTextView#24]
Create a new line, then tap in any line above that new line, paste the contents on the UITextView. The constraints break instantly.

**Comment by cvcoder1** [comment]
Pastes from new lines work. Paste from previous line does not work.

**Comment by ruslanskorb** [comment]
Hey, @cvcoder1.

Are you using constraints or are you changing the frame manually? Could you isolate the problem in a sample project? I would take a look at it.

At the moment, the paste action in the "RSKGrowingTextViewExample" project is working as expected.

https://user-images.githubusercontent.com/1182823/220198595-cae2e506-551a-47f4-a013-553e5521b3fc.mp4

**Comment by ruslanskorb** [comment]
If the problem still exists, feel free to reopen the issue.
