### ISSUE TITLE
Problem with UITableViewCell

### ISSUE THREAD

**Issue by ayon115** [ruslanskorb/RSKGrowingTextView#3]
Hi,
I am using this class within a UITableViewCell. Problem is it's not expanding or height is not changing after 3 lines. And TableView's cell height also does not change when I am entering texts. Any hint on how to solve it ?

**Comment by ruslanskorb** [comment]
Hi @ayon115,
Sorry for the delayed response.
`RSKGrowingTextView` is not intended to be used inside `UITableViewCell`. You have to manage the height of the cell manually.
I can suggest you to use [`RSKPlaceholderTextView`](https://github.com/ruslanskorb/RSKPlaceholderTextView) inside `UITableViewCell`. You need to add top / bottom / leading / trailing constraints to it and calculate the height of the text view `NSLayoutManager`.

**Comment by ayon115** [comment]
@ruslanskorb Nevermind, I solved that problem. Things are good.

**Comment by ruslanskorb** [comment]
@ayon115 :thumbsup:

**Comment by hunaid-hassan-confiz** [comment]
How exactly did u solve the problem?
Need something similar in my project. Would love a solution

**Comment by ayon115** [comment]
It's pretty easier than I thought. I'll write a blog post about it and share with you this weekend. @hunaid-hassan-confiz

**Comment by hunaid-hassan-confiz** [comment]
Hey sorry for being impatient but I really need to figure this out. Any pointers you can give me? @ayon115

**Comment by ayon115** [comment]
@hunaid-hassan-confiz Please check my repo. I have done a sample project demonstrating the process. Hope it will help.
https://github.com/ayon115/AZAutoGrowingTextView

**Comment by hunaid-hassan-confiz** [comment]
Thanks @ayon115 👍
