### ISSUE TITLE
Placeholder descenders are clipped

### ISSUE THREAD

**Issue by emuye** [ruslanskorb/RSKGrowingTextView#4]
If you set the textContainerInsets to have a different top and bottom inset, descenders will be clipped on the placeholder text.

Here are the settings to use:

``` swift
  self.growingTextView.font = UIFont.systemFontOfSize(14, weight: UIFontWeightRegular)
  self.growingTextView.textContainerInset = UIEdgeInsets(top: 21, left: 10, bottom: 18, right: 10)
```

**Comment by ruslanskorb** [comment]
Hi @emuye!

Thank you for raising the issue!
The fix is available from the version [1.1.1](https://github.com/ruslanskorb/RSKGrowingTextView/releases/tag/1.1.1) :sparkles:

Happy Coding!
