### ISSUE TITLE
How can I tigger height change programatically

### ISSUE THREAD

**Issue by hhunaid** [ruslanskorb/RSKGrowingTextView#5]
If I set the text programatically it doesnt change the constraints. Maybe you can trigger the height change on `didSet` of `text`

**Comment by hhunaid** [comment]
Nevermind I can just set minimumNumberOfLines to 1 for the same effect

**Comment by ruslanskorb** [comment]
@pureblood If the content of the text view was changed, either programmatically or by entering the text by the user, `RSKGrowingTextView` will recalculate and update its height. Therefore, you should never trigger height change programatically.
When you changes the text in the text view programatically, UIKit transforms it to the attributed text and calls `didSet` of `attributedText`.
If you need to force relayout of the text view you can always call `textView.superview?.layoutIfNeeded()`

**Comment by ruslanskorb** [comment]
@pureblood If you have any other questions about using `RSKGrowingTextView` feel free to ask.
