### ISSUE TITLE
No such module 'RSKKeyboardAnimationObserver'

### ISSUE THREAD

**Issue by waseefakhtar** [ruslanskorb/RSKGrowingTextView#8]
I’m working on Swift 2.3 using RSKGrowingTextView 1.2.0. I can’t seem to import `RSKKeyboardAnimationObserver` in my ViewController. Neither can I find the methods `rsk_subscribeKeyboardWithBeforeWillShowOrHideAnimation` and `rsk_subscribeKeyboardWithWillChangeFrameAnimation` to implement. What do I do?

**Comment by ruslanskorb** [comment]
**RSKKeyboardAnimationObserver** is not a part of **RSGrowingTextView**. To use it you need to add `pod RSKKeyboardAnimationObserver` to your **Podfile** and run `pod install`.
