### ISSUE TITLE
Issue resizing the textView

### ISSUE THREAD

**Issue by chashmeetsingh** [ruslanskorb/RSKGrowingTextView#9]
The textView is not resizing itself. I have tried using `inputTextView.superview?.layoutIfNeeded()` for forcing it to update height but it isn't.

My project: https://github.com/chashmeetsingh/susi_iOS/blob/issue89/Susi/Controllers/MainViewController/MainViewController.swift#L141

https://github.com/chashmeetsingh/susi_iOS/blob/issue89/Susi/Controllers/MainViewController/MainVCMethods.swift#L183

Please let me know if something wrong with the usage or declaration. thanks! @ruslanskorb

**Comment by ruslanskorb** [comment]
@chashmeetsingh https://github.com/chashmeetsingh/susi_iOS/blob/issue89/Susi/Controllers/MainViewController/MainViewController.swift#L146

**Comment by chashmeetsingh** [comment]
Setting it to 4 doesn't resize the text view. The height remains the same.

**Comment by ruslanskorb** [comment]
@chashmeetsingh https://github.com/chashmeetsingh/susi_iOS/blob/issue89/Susi/Controllers/MainViewController/MainVCMethods.swift#L186

```swift
format: "V:[v0(>=44)]"
```

**Comment by chashmeetsingh** [comment]
My bad. Thanks, that was it.

**Comment by ruslanskorb** [comment]
:thumbsup:
